### ISSUE TITLE
Pybind `make` error

### ISSUE THREAD

**Issue by yasirroni** [nadfity/omnetpy#1]
I'm trying to `make` pybind for the latest module (`getSystemModule`). The following error occured:
 
```
 py_cChannel_Result.def_readwrite("remainingDuration", &omnetpp::cChannel::Result::remainingDuration);
      |                        ^~~~~~~~~~~~~
bind_cchannel.cc:36:79: error: ‘omnetpp::cChannel::Result’ has not been declared
   36 |     py_cChannel_Result.def_readwrite("remainingDuration", &omnetpp::cChannel::Result::remainingDuration);
```

**Comment by Abdillah** [comment]
Please compile against `omnetpp-6.0pre10` as what the Dockerfile defined.
This error happened because `cChannel::Result` has new attribute / property not existed in prior version.

**Comment by yasirroni** [comment]
Old omnetpy using 6.0ppre8 no longer supported.
